// <auto-generated />
using System;
using BTCPayServer.Plugins.OpenSimulator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTCPayServer.Plugins.OpenSimulator.Migrations
{
    [DbContext(typeof(OpenSimulatorDbContext))]
    partial class OpenSimulatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.OpenSimulator")
                .HasAnnotation("ProductVersion", "0.1.2");

            modelBuilder.Entity("BTCPayServer.Plugins.OpenSimulator.Data.OpenSimulatorData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarId")
                        .HasColumnType("TEXT");
                    
                    b.Property<string>("AvatarHomeURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .HasColumnType("TEXT");


                    b.Property<string>("ObjectRegion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectURL")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ObjectAuthorization")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("AvatarId");

                    b.HasIndex("ObjectId");

                    b.ToTable("Authorizations");
                });
#pragma warning restore 612, 618
        }
    }
}
